### ISSUE TITLE
Exception when indexing a project

### ISSUE THREAD

**Issue by AndreaCrotti** [jpmonettas/clograms#18]
I just tried to index one of my toy projects
https://github.com/AndreaCrotti/elo/

with this command:
`clj -Sdeps '{:deps {clograms {:mvn/version "0.1.13"}}}' -m clograms.server --platform clj .`

and it fails with this exception:

```Indexing done, open http://localhost:3000
Wed Jul 22 15:19:38 BST 2020 [worker-2] ERROR - GET /db
java.lang.RuntimeException: java.lang.Exception: Not supported: class java.util.regex.Pattern
	at com.cognitect.transit.impl.WriterFactory$1.write(WriterFactory.java:65)
	at cognitect.transit$write.invokeStatic(transit.clj:167)
	at cognitect.transit$write.invoke(transit.clj:164)
	at clograms.core$db_edn.invokeStatic(core.clj:46)
	at clograms.core$db_edn.invoke(core.clj:39)
	at clograms.handler$build_routes$fn__10361.invoke(handler.clj:32)
	at compojure.core$wrap_response$fn__4049.invoke(core.clj:158)
	at compojure.core$wrap_route_middleware$fn__4033.invoke(core.clj:128)
	at compojure.core$wrap_route_info$fn__4038.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__4042.invoke(core.clj:146)
	at compojure.core$routing$fn__4057.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at clojure.core$some.invoke(core.clj:2692)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at compojure.core$routes$fn__4061.invoke(core.clj:192)
	at compojure.core$routing$fn__4057.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at clojure.core$some.invoke(core.clj:2692)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at compojure.core$routes$fn__4061.invoke(core.clj:192)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.cljc:178)
	at ring.middleware.cors$handle_cors.invoke(cors.cljc:167)
	at ring.middleware.cors$wrap_cors$fn__11084.invoke(cors.cljc:205)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__11013.invoke(keyword_params.clj:53)
	at ring.middleware.params$wrap_params$fn__10969.invoke(params.clj:67)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:115)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.Exception: Not supported: class java.util.regex.Pattern
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:194)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:102)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.AbstractEmitter.emitTagged(AbstractEmitter.java:49)
	at com.cognitect.transit.impl.AbstractEmitter.emitEncoded(AbstractEmitter.java:74)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:187)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:102)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.AbstractEmitter.emitTagged(AbstractEmitter.java:49)
	at com.cognitect.transit.impl.AbstractEmitter.emitEncoded(AbstractEmitter.java:74)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:187)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:102)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.AbstractEmitter.emitTagged(AbstractEmitter.java:49)
	at com.cognitect.transit.impl.AbstractEmitter.emitEncoded(AbstractEmitter.java:74)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:187)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:97)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:102)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.AbstractEmitter.emitTagged(AbstractEmitter.java:49)
	at com.cognitect.transit.impl.AbstractEmitter.emitEncoded(AbstractEmitter.java:74)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:187)
	at com.cognitect.transit.impl.JsonEmitter.emitMap(JsonEmitter.java:171)
	at com.cognitect.transit.impl.AbstractEmitter.emitMap(AbstractEmitter.java:85)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:184)
	at com.cognitect.transit.impl.AbstractEmitter.marshalTop(AbstractEmitter.java:211)
	at com.cognitect.transit.impl.JsonEmitter.emit(JsonEmitter.java:41)
	at com.cognitect.transit.impl.WriterFactory$1.write(WriterFactory.java:62)
	... 38 more
```

**Comment by AndreaCrotti** [comment]
I tried another Clj only project and it works fine, even though the save button doesn't seem to do anything and I don't see any errors.
Maybe it was failing because that first project was both clj and cljs?

**Comment by daemianmack** [comment]
> the save button doesn't seem to do anything

I just stumbled over this myself -- look for a "diagram.edn" file in the directory from which you ran your `clj` command.

**Comment by jpmonettas** [comment]
Hey thanks for reporting that @AndreaCrotti.

Looks like indexing your project as a ClojureScript project works fine `clj -Sdeps '{:deps {clograms {:mvn/version "0.1.13"}}}' -m clograms.server --platform cljs .`

That error looks related to a Clojure file in the dependency tree that is using a regex pattern that is making transit fail.
Looks like there is a datom in the datascript db that can't be serialized by transit, will try to figure it out.

**Comment by jpmonettas** [comment]
@AndreaCrotti @daemianmack yeah that save and restore functionality is very bare bones, I'm not sure how many people find this project useful to put more effort into it. It works but still experimental.

**Comment by jpmonettas** [comment]
Found the culprit:
 
`[:db/add 1080028070 :multi/dispatch-form (fn [encryptedpassword] (-> encryptedpassword (str/split #"\$") (first) (keyword)))]

Was trying to serialize a clojure form as edn, which is wrong since edn can't contain regexp patterns.
Now `:multi/dispatch-form` is serializing as string the same way that `:source/form` does.

Looks like 0.1.14 is indexing your project fine now for Clojure and ClojureScript. Please reopen if you still see the issue.

**Comment by AndreaCrotti** [comment]
Ah nice thanks @jpmonettas
