### ISSUE TITLE
conflict with ubergraph (exception on startup)

### ISSUE THREAD

**Issue by boxxxie** [jpmonettas/clograms#36]
`./clojure/deps.edn`
```clojure
:aliases {
           :clograms {
                      :extra-deps {
                                   ;; code base doc/viewer
                                   ;; https://github.com/jpmonettas/clograms
                                   ;; clj -Sforce -M:clograms -m clograms.server --platform clj clojure-project-folder
                                   com.github.jpmonettas/clograms {:mvn/version "0.1.141"}
                                   }
                      }
}
```

project deps.edn
`ubergraph/ubergraph {:mvn/version "0.8.2"}`

command `clj -Sforce -M:clograms -m clograms.server --platform clj .`

```
Exception in thread "main" Syntax error compiling at (ubergraph/core.clj:963:44).
        at clojure.lang.Compiler.analyze(Compiler.java:6825)
        at clojure.lang.Compiler.analyze(Compiler.java:6762)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3832)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7126)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyze(Compiler.java:6762)
        at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2841)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6401)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyze(Compiler.java:6762)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6453)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyze(Compiler.java:6762)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6453)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyze(Compiler.java:6762)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5479)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4041)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:596)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
        at clojure.lang.Compiler.analyze(Compiler.java:6806)
        at clojure.lang.Compiler.analyze(Compiler.java:6762)
        at clojure.lang.Compiler.eval(Compiler.java:7198)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)
        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.invoke(RestFn.java:3894)
        at nvestiv.config.core$eval7499$loading__6789__auto____7500.invoke(core.clj:1)
        at nvestiv.config.core$eval7499.invokeStatic(core.clj:1)
        at nvestiv.config.core$eval7499.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7183)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)
        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.invoke(RestFn.java:3894)
        at user$eval140$loading__6789__auto____141.invoke(user.clj:1)
        at user$eval140.invokeStatic(user.clj:1)
        at user$eval140.invoke(user.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7183)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:368)
        at clojure.lang.RT.maybeLoadResourceScript(RT.java:364)
        at clojure.lang.RT.doInit(RT.java:486)
        at clojure.lang.RT.init(RT.java:467)
        at clojure.main.main(main.java:38)
Caused by: java.lang.RuntimeException: No such var: d/save!
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.resolveIn(Compiler.java:7405)
        at clojure.lang.Compiler.resolve(Compiler.java:7375)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7336)
        at clojure.lang.Compiler.analyze(Compiler.java:6785)
        ... 111 more
```

i did have code that was actually making a .dot of my clojure dep tree, that file was being pointed at in the initial exceptions. i commented out all the code in that file. still got error.

i then removed ubergraph from my code completely, including deps. 
```
Downloading: ubergraph/ubergraph/0.8.1/ubergraph-0.8.1.pom from clojars
Downloading: ubergraph/ubergraph/0.8.1/ubergraph-0.8.1.jar from clojars
```
running the program again downloaded a different ubergraph (i'm guessing one of the deps in this codebase is using ubergraph).
the same exception persists.

**Comment by jpmonettas** [comment]
Interesting, I'll take a look. Thanks for reporting it!

**Comment by boxxxie** [comment]
i'll post another issue after this one is fixed, cus i'm getting exceptions for my use of `tools.namespace` as well. maybe fixing this will also fix that

**Comment by jpmonettas** [comment]
Ok, I just got to try this but wasn't able to reproduce the issue, so still not sure.
This is what I tried, created a empty project with a  deps.edn like this :
```
{:paths ["src"]
 :deps {ubergraph/ubergraph {:mvn/version "0.8.2"}}
 :aliases {:clograms {:extra-deps {com.github.jpmonettas/clograms {:mvn/version "0.1.141"}}
                      :main-opts ["-m" "clograms.server" "--platform" "clj" "."]}}}
```
and then run `clj -M:clograms`

Didn't see any exceptions.

![latest-screenshot](https://github.com/jpmonettas/clograms/assets/786299/26cc3494-1fc5-4361-9d07-d589b5476a5b)

**Comment by jpmonettas** [comment]
Regarding `tools.namespace` yeah, that is an issue that I'll address soon. The thing is that currently Clograms uses a patched version of tools.namespace, so if you use tools.namespace in your project it should show a message on the console that tells you to remove your version for creating the diagram.This is annoying and I'll revisit it soon, but it is a known issue.

**Comment by boxxxie** [comment]
I'll investigate further.
maybe tools.namespace is the issue all along. i'll play around with my project a bit on the weekend to see if i can make progress with it using this tool

**Comment by jpmonettas** [comment]
@boxxxie sure, I'm on Clojurians slack under the same handle if you want to troubleshoot something a little faster.
